### PR TITLE
Performance and memory fixes

### PR DESCRIPTION
**Pull request by krzysiek1507**
It should be a little bit faster (or a lot faster in some cases) and use less memory.

### CODE REVIEW

**Comment by krzysiek1507** [comment]
```ruby
lib/hashdiff/util.rb:11:20: C: Use (count_a + count_b).zero? instead of count_a + count_b == 0.
    return true if count_a + count_b == 0
                   ^^^^^^^^^^^^^^^^^^^^^^
```
In fact `number.zero?` is about 30% slower than `number == 0`.

**Comment by krzysiek1507** [comment]
If it is easier to review, I can split it into smaller PRs.

**Comment by liufengyun** [comment]
Thanks @krzysiek1507 -- One PR is fine. I'm wondering why some test failed, could you have a look?

**Comment by krzysiek1507** [comment]
It's rubocop and this particular rule doesn't make sense in this case.

```ruby
lib/hashdiff/util.rb:85:5: C: Style/IfUnlessModifier: Favor modifier if usage when having a single-line body. Another good alternative is the usage of control flow &&/||.
    if options[:numeric_tolerance].is_a?(Numeric) && obj1.is_a?(Numeric) && obj2.is_a?(Numeric)
    ^^
```

**Comment by krzysiek1507** [comment]
Some stats:

```ruby
obj1 = obj2 = []

Warming up --------------------------------------
              master    49.253k i/100ms
Calculating -------------------------------------
              master    590.795k (± 2.1%) i/s -      2.955M in   5.004451s
Calculating -------------------------------------
              master   856.000  memsize (     0.000  retained)
                         7.000  objects (     0.000  retained)
                         0.000  strings (     0.000  retained)

Warming up --------------------------------------
           optimized    82.442k i/100ms
Calculating -------------------------------------
           optimized      1.140M (± 1.8%) i/s -      5.771M in   5.061820s
Calculating -------------------------------------
           optimized   544.000  memsize (     0.000  retained)
                         4.000  objects (     0.000  retained)
                         0.000  strings (     0.000  retained)

================================================

obj1 = obj2 = {}

Warming up --------------------------------------
              master    24.736k i/100ms
Calculating -------------------------------------
              master    274.993k (± 5.6%) i/s -      1.385M in   5.059656s
Calculating -------------------------------------
              master     1.024k memsize (     0.000  retained)
                        16.000  objects (     0.000  retained)
                         0.000  strings (     0.000  retained)

Warming up --------------------------------------
           optimized    25.828k i/100ms
Calculating -------------------------------------
           optimized    314.045k (± 5.0%) i/s -      1.576M in   5.032663s
Calculating -------------------------------------
           optimized   824.000  memsize (     0.000  retained)
                        11.000  objects (     0.000  retained)
                         0.000  strings (     0.000  retained)

================================================

obj1 = { a: 1, b: { b2: [], b3: [{ b4: 1 }] }, h: [1, 2, 3, 4, 5], i: 2, j: 2, k: [] }
obj2 = { a: 1, b: { b2: [], b3: [{ b4: 1 }] }, g: [1, 2, 3, 4, 5], i: 2, j: 4, k: {} }

Warming up --------------------------------------
              master     1.540k i/100ms
Calculating -------------------------------------
              master     15.653k (± 8.4%) i/s -     78.540k in   5.072408s
Calculating -------------------------------------
              master    14.608k memsize (     0.000  retained)
                       164.000  objects (     0.000  retained)
                        17.000  strings (     0.000  retained)

Warming up --------------------------------------
           optimized     1.789k i/100ms
Calculating -------------------------------------
           optimized     18.383k (± 2.6%) i/s -     93.028k in   5.063884s
Calculating -------------------------------------
           optimized    12.592k memsize (     0.000  retained)
                       128.000  objects (     0.000  retained)
                        17.000  strings (     0.000  retained)
```

**Comment by liufengyun** [comment]
Thanks @krzysiek1507. Maybe we can silence rubocop in that case?

**Comment by krzysiek1507** [comment]
@liufengyun done!

**Comment by liufengyun** [comment]
Thanks a lot @krzysiek1507 🎉

**Pull request merged**
