### PR TITLE
Remove warning

### LINKED ISSUE #66: Please stop the `warn` spam
now every test run/boot has a warning :(
Just remove the constant and be done with it ... or do whatever activesupport does but only when a deprecated constant is used

caused by https://github.com/liufengyun/hashdiff/pull/65

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #66: Remove warning

### CODE REVIEW

**Comment by liufengyun** [comment]
@jfelchner WDYT?

**Comment by krzysiek1507** [comment]
I think the warning should be here. Only `HashDiff` should be deprecated.

**Comment by krzysiek1507** [comment]
Or you can remove the warning and release 1.0.

**Comment by jfelchner** [comment]
@liufengyun unless it's causing issues, the warning needs to remain until `1.0`.  And we shouldn't release `1.0` just yet.

**Comment by jfelchner** [comment]
If `webmock` had a `< 1.0` in their gemspec, we could release `1.0` right now, but they don't. So if we upgrade `hashdiff` to `1.0` before they merge my PR. If we do, we'll break every `webmock` install.

**Comment by liufengyun** [comment]
Thanks a lot @krzysiek1507 @jfelchner .

/cc: @grosser, do you have any proposals?

**Comment by grosser** [comment]
My order of preference:
 - remove the warning, since 99% of users don't care that it collides with some other random gem
 - make the warning show when using the deprecated constant name
 - release 1.0 with the constant switched

**Comment by jfelchner** [comment]
@grosser without a warning, there's less of a chance they're going to update, which means there's more of a chance it's going to break their apps.  We have had people be driven to the GH issue specifically because of the warning.

If you know of a way to make the warning show only when using the deprecated constant, I'm all for that solution, but I don't know how to do that.

**Comment by grosser** [comment]
there is no update, so people just come here and complain, that's not a solution 🤷‍♂ 
... remove the warning and add it back once there is a v1 and nobody would have opened an issue

**Comment by jfelchner** [comment]
@grosser *I* opened the issue.  Before the warning was even added.  And we would release a v1 if it were possible, but it is not yet until we get a new `webmock` version released.

**Pull request closed without merging**
